//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_treatment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail_Record
    {
        public string M_ID { get; set; }
        public System.DateTime Send_Date { get; set; }
        public string Medicine { get; set; }
        public string Zipcode { get; set; }
        public string Addr { get; set; }
        public string PH_ID { get; set; }
    
        public virtual Medical_records Medical_records { get; set; }
    }
}
