//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_treatment
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Mail_Record> Mail_Record { get; set; }
        public virtual DbSet<Medical_records> Medical_records { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<Prove> Prove { get; set; }
        public virtual DbSet<Receipt> Receipt { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
