//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_treatment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Medical_records = new HashSet<Medical_records>();
        }
    
        public int P_ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Firstvisit_Date { get; set; }
        public string Sex { get; set; }
        public string identity { get; set; }
        public Nullable<System.DateTime> Born_Date { get; set; }
        public string Phone { get; set; }
        public string addr { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medical_records> Medical_records { get; set; }
    }
}
